/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.PersistenciaJPA;
import model.Agendamento;
import model.Prontuario;
import javax.swing.*;
import java.time.LocalDate;

/**
 *
 * @author marco
 */
public class FormProntuario extends javax.swing.JFrame {
    private Prontuario prontuario;
    private Agendamento agendamento; // Guarda a referência do agendamento pai
    private final PersistenciaJPA dao;    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormProntuario.class.getName());

    /**
     * Creates new form FormProntuario
     */
    public FormProntuario(Agendamento agendamento) {
        initComponents();
        this.dao = new PersistenciaJPA();
        this.agendamento = agendamento;
        
        // Verifica se o agendamento JÁ TEM um prontuário associado
        if (agendamento.getProntuario() != null) {
            // Se sim, estamos em modo de EDIÇÃO
            setTitle("Editar Prontuário");
            this.prontuario = agendamento.getProntuario();
            preencherCampos();
        } else {
            // Se não, estamos em modo de CRIAÇÃO
            setTitle("Novo Prontuário");
            this.prontuario = new Prontuario();
            this.prontuario.setData(LocalDate.now()); // Pega a data de hoje
        }
    }
    
    private void preencherCampos() {
        jtaDiagnostico.setText(prontuario.getDiagnostico());
        jtaTratamento.setText(prontuario.getTratamento());
        jtaAnotacoes.setText(prontuario.getAnotacoes());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDiagnostico = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaTratamento = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaAnotacoes = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Diagnóstico:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jtaDiagnostico.setColumns(20);
        jtaDiagnostico.setRows(5);
        jScrollPane1.setViewportView(jtaDiagnostico);

        jtaTratamento.setColumns(20);
        jtaTratamento.setRows(5);
        jScrollPane2.setViewportView(jtaTratamento);

        jLabel2.setText("Tratamento");

        jtaAnotacoes.setColumns(20);
        jtaAnotacoes.setRows(5);
        jScrollPane3.setViewportView(jtaAnotacoes);

        jLabel3.setText("Anotações:");

        jLabel4.setText("Proposto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnSalvar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCancelar))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(242, 242, 242)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel4))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        prontuario.setDiagnostico(jtaDiagnostico.getText());
        prontuario.setTratamento(jtaTratamento.getText());
        prontuario.setAnotacoes(jtaAnotacoes.getText());

        try {
            // Associa o prontuário ao agendamento (relação bidirecional)
            this.agendamento.setProntuario(this.prontuario);
            
            // <<< O TRUQUE FINAL:
            // Em vez de salvar o prontuário, nós atualizamos o AGENDAMENTO.
            // Como a relação está com "cascade = CascadeType.ALL", o JPA
            // vai salvar/atualizar o prontuário automaticamente junto.
            // É mais seguro e garante a integridade da relação.
            dao.merge(this.agendamento); 
            
            JOptionPane.showMessageDialog(this, "Prontuário salvo com sucesso!");
            dispose(); // Fecha a tela

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar prontuário: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jtaAnotacoes;
    private javax.swing.JTextArea jtaDiagnostico;
    private javax.swing.JTextArea jtaTratamento;
    // End of variables declaration//GEN-END:variables
}
