package view;

/**
 *
 * @author marco
 */
public class FormSobre extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormSobre.class.getName());

    /**
     * Creates new form FormSobre
     */
    public FormSobre() {
            initComponents();

            txtGuia.setText(
                "PROJETO FINAL - GESTÃO DE CLÍNICA ODONTOLÓGICA\n\n"
              + "Objetivo:\n"
              + "- Criar uma aplicação Java para gerenciar operações de uma clínica.\n\n"
              + "Funcionalidades:\n"
              + "- Cadastro de Pacientes, Dentistas\n"
              + "- Agendamento de Consultas\n"
              + "- Registro de Prontuários\n\n"
              + "Fluxo de Uso:\n"
              + "1. Cadastre Paciente e Dentista\n"
              + "2. Agende a Consulta\n"
              + "3. Registre o Prontuário após atendimento\n\n"
              + "Requisitos:\n"
              + "- Java, PostgreSQL, Maven\n\n"
              + "Autor: Marco Felipi\n"
              + "Disciplina: LPOO, IFSul"
            );
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtGuia = new javax.swing.JTextArea();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtGuia.setEditable(false);
        txtGuia.setColumns(20);
        txtGuia.setLineWrap(true);
        txtGuia.setRows(5);
        txtGuia.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtGuia);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVoltar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoltar)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtGuia;
    // End of variables declaration//GEN-END:variables

}